export const siteConfig = {
  name: "CmdTab",
  tagline: "Choose the exact Mac window, not just the app.",
  description:
    "CmdTab is a standalone macOS window-switcher app, separate from Apple’s Command-Tab shortcut, with individual window previews, search, quick actions, and exact-window recency.",
  defaultSiteUrl: "https://cmdtab.net",
  socialImagePath: "/og/cover.png",
  nav: [
    { label: "Modes", href: "#modes" },
    { label: "Walkthrough", href: "#walkthrough" },
    { label: "Features", href: "#details" },
    { label: "Buy", href: "/buy" },
  ],
  ctas: {
    primary: "Start the trial",
    secondary: "See the walkthrough",
    tertiary: "Read the privacy policy",
  },
  keywords: [
    "CmdTab",
    "CmdTab macOS app switcher",
    "CmdTab window switcher",
    "Mac app switcher",
    "custom macOS app switcher",
    "Cmd+Tab alternative",
    "window previews for Mac",
    "app switcher with thumbnails",
    "Mac window switcher with quick actions",
    "Mac app switcher with search memory",
    "display-aware app switcher for Mac",
    "Mac app beta waitlist",
    "macOS productivity beta",
    "one-time license for Mac utility",
    "Mac utility free trial",
  ],
  contactEmail: "tohsh17@gmail.com",
} as const;
